<h1>Reading the Holy Bible</h1>
<form method="post" action="<?php echo $this->url('bible-home',['controller'=>'index', 'action'=>'read'])?>">
<ul>
    <?php foreach ($this->planos as $plano):?>
    <li>
        <button type="submit" name="button" class="btn btn-link"value="<?php echo $plano->id;?>"><?php echo $plano->name;?></button>
    </li>
    <?php endforeach;
 var_dump($book);
    ?>
</ul>
</form>