<?php
$next = ($this->book['chapter'] < $this->book['totalChapters']) ? $this->book['chapter'] + 1 : $this->book['chapter'];
$prev = ($this->book['chapter'] > 1) ? $this->book['chapter'] - 1 : $this->book['chapter'];
?>
<div class="row">
    <form method="post" action="<?php echo $this->url('bible-home', ['controller' => 'index', 'action' => 'read']) ?>">
        <div class="col-md-8">
            <h1><?php echo $this->book['nameBook']->name . ' - ' . $this->book['chapter']; ?></h1>
            <ol>
                <?php foreach ($this->verses as $verse): ?>
                    <li><?php echo $verse; ?></li>
                <?php endforeach; ?>
            </ol>

            <nav>
                <ul class="pager">
                    <li class="previous"><button name="chapter" value="<?php echo $prev; ?>"><span aria-hidden="true">&larr;</span> Anterior</button></li>
                    <li class="next"><button name="chapter" value="<?php echo $next; ?>">Próximo <span aria-hidden="true">&rarr;</span></button></li>
                </ul>
            </nav>
        </div>
        <div class="col-md-4">
            <div class="row">
                <h3>Chapters</h3>
                <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                    <div class="btn-group" role="group" aria-label="First group">
                        <?php for ($i = 0; $i < $this->book['totalChapters']; $i++): ?>
                            <button type="submit" class="btn btn-default" name="chapter" value="<?php echo $i + 1 ?>"><?php echo $i + 1 ?></button>

                        <?php endfor; ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <h3>Select the Version</h3>
                <select id="version" name="version">
                    <option value="aa"> AA</option>
                    <option value="nvi"> NVI</option>
                </select>
                <button type="submit" class="btn btn-default" >Trocar Versao</button>
            </div>
        </div>
    </form>
</div>