<div class="row">
    <div class="col-lg-4">

<?php
    $form = $this->livroForm;
    
    if(isset($this->data)){
        $form->get('liv_id')->setAttributes(['value'=>$this->data['liv_id']]);
        $form->get('liv_title')->setAttributes(['value'=>$this->data['liv_title']]);
        $form->get('liv_cat_id')->setAttributes(['value'=>$this->data['liv_cat_id']]);
        $form->get('liv_description')->setAttributes(['value'=>$this->data['liv_description']]);
        $form->get('liv_author')->setAttributes(['value'=>$this->data['liv_author']]);
        if(!is_null($this->data['liv_img_url'])){
            $img = '<img src=http://'.$_SERVER['HTTP_HOST']."/".$this->data['liv_img_url'].' height="100" />';
        }
        
    }
    
    $form->setAttribute('action', $this->url('livraria-admin', ['controller' => 'livros', 'action' => 'add']));
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('liv_id'));
    echo $this->formRow($form->get('liv_title'));
    echo $this->formRow($form->get('liv_cat_id'));
    echo $this->formRow($form->get('liv_description'));
    echo $this->formRow($form->get('liv_author'));
    echo $this->formRow($form->get('liv_img'));
    echo (!is_null($img) ? ($img."<br>") : "<br>");
    echo $this->formRow($form->get('submit'));
    echo $this->form()->closeTag();
?>

    </div>
</div>