<div class="row">
    <div class="col-lg-4">

<?php
    $form = $this->form;
    
    if(isset($this->data)){
        $form->get('liv_id')->setAttributes(['value'=>$this->data['liv_id']]);
        $form->get('liv_title')->setAttributes(['value'=>$this->data['liv_title']]);
        $form->get('liv_cat_id')->setAttributes(['value'=>$this->data['liv_cat_id']]);
        $form->get('liv_description')->setAttributes(['value'=>$this->data['liv_description']]);
        $form->get('liv_author')->setAttributes(['value'=>$this->data['liv_author']]);
        if(!is_null($this->data['liv_img_url'])){
            $img = '<img src=http://'.$_SERVER['HTTP_HOST']."/".$this->data['liv_img_url'].' height="100" />';
        }
        
    }
    if(isset($this->error)){
        echo "<h3>{$this->error}</h3>";
    }
    $form->setAttribute('action', $this->url('admin-login'));
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('email'));
    echo $this->formRow($form->get('password'));
    echo $this->formRow($form->get('submit'));
    echo $this->form()->closeTag();
?>

    </div>
</div>