
<div class="row">
    <div class="col-lg-4">
    
<?php

$form = $this->postForm;
#var_dump($this->data);
if(isset($this->data)){
    $form->get('cat_id')->setAttributes(['value'=>$this->data['cat_id']]);
    $form->get('cat_title')->setAttributes(['value'=>$this->data['cat_title']]);
    $form->get('cat_description')->setAttributes(['value'=>$this->data['cat_description']]);
    if(!is_null($this->data['cat_img_url']))
        $img = '<img src=http://'.$_SERVER['HTTP_HOST']."/".$this->data['cat_img_url'].' height="100" />';
}


$form->prepare();
$form->setAttribute('action', $this->url('livraria-admin', ['controller'=>'categorias', 'action'=>'add']));

echo $this->form()->openTag($form);
echo $this->formRow($form->get('cat_id'))."<br>";
echo $this->formRow($form->get('cat_title'))."<br>";
echo $this->formRow($form->get('cat_description'))."<br>";
echo $this->formRow($form->get('cat_img'));
echo (!is_null($img) ? ($img."<br>") : "<br>");
echo $this->formSubmit($this->postForm->get('submit'))."<br>";
echo $this->form()->closeTag();

?>
    
    </div>
</div>