<h1>Categorias Admin</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Description</th>
            <th>Image</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->categorias as $data):?>
        <tr>
            <td><?php echo $data->getId();?></td>
            <td><?php echo $data->getTitle();?></td>
            <td><?php echo $data->getDescription();?></td>
            <td><img src="<?php echo $data->getImageUrl();?>" width="50" height="50" /></td>
            <td>
                <a href="<?php echo $this->url('livraria-admin', ['action'=>'form', 'id'=>$data->getId()]);?>"><span class="glyphicon glyphicon-pencil"></span></a>
                <a href="<?php echo $this->url('livraria-admin', ['action'=>'delete', 'id'=>$data->getId()]);?>"><span class="glyphicon glyphicon-trash"></span></a>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<br>
<a href="<?php echo $this->url('livraria-admin', ['action'=>'form']);?>" class="btn btn-primary">Nova</a>

