<div class="row">
    <div class="col-lg-4">

<?php
    $form = $this->form;
    if(isset($this->data)){
        $form->get('liv_id')->setAttributes(['value'=>$this->data['liv_id']]);
        $form->get('liv_title')->setAttributes(['value'=>$this->data['liv_title']]);
        $form->get('liv_cat_id')->setAttributes(['value'=>$this->data['liv_cat_id']]);
        $form->get('liv_description')->setAttributes(['value'=>$this->data['liv_description']]);
        $form->get('liv_author')->setAttributes(['value'=>$this->data['liv_author']]);
        
    }
    
    $form->setAttribute('action', $this->url('livraria', ['controller' => 'user', 'action' => 'add']));
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('id'));
    echo $this->formRow($form->get('name'));
    echo $this->formRow($form->get('email'));
    echo $this->formRow($form->get('password'));
    echo $this->formRow($form->get('submit'));
    echo $this->form()->closeTag();
?>

    </div>
</div>